name: Preprocessing

on:
  push:
    paths:
      - 'house-price-india_raw.csv'
      - 'preprocessing/automate_Muhammad-Raihan-Fauzi.py'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Muhammad-Raihan-Fauzi.py

      - name: Commit preprocessed data
        run: |
          git config user.name "mraihanfauzii"
          git config user.email "muhammad.raihan.fauzi@gmail.com"
          git add house-price-india_preprocessed.csv
          git commit -m "Update preprocessed dataset"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}